spring:
  cloud:
    stream:
      bindings:
        anomalies:
          destination: amq.topic
          binder: rabbit
        breaking:
          destination: amq.topic
          binder: rabbit
      rabbit:
        bindings:
          anomalies:
            producer:
          breaking:
            consumer:
              queueNameGroupOnly: true
  rabbitmq:
    password: pass
    username: user