spring:
  cloud:
    stream:
      bindings:
        input:
          destination: amq.topic
          binder: rabbit
          group: messages-consumer-group
      rabbit:
        bindings:
          input:
            consumer:
              queueNameGroupOnly: true
            producer:
              routing-key-expression: '".my.topic"'
  rabbitmq:
    password: pass
    username: user