spring:
  cloud:
    stream:
      bindings:
        input:
          destination: amq.topic
          binder: rabbit
          group: consumer-group-marcin
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: ".cars.marcin"
              queueNameGroupOnly: true
  rabbitmq:
    password: pass
    username: user